### PR TITLE
Update the name attribute & extract name

### PR DESCRIPTION
**Pull request by arn-the-long-beard**
Hello :smile: 

I was thinking that it could be nice to rename the attribute "name" to path since it is actually a path. 

What do you think about it ?

### CODE REVIEW

**Comment by mankinskin** [comment]
Yes that was also my first idea, however `path` is a [built-in attribute](https://doc.rust-lang.org/reference/items/modules.html#the-path-attribute) and I couldn't get it to work.

**Comment by mankinskin** [comment]
If you want to try it out you will also need to change the attribute name in the `#[proc_macro_derive(...)]` part

**Comment by arn-the-long-beard** [comment]
Yes you are right ! I made the change in the proc macro and it worked strangely.

**Comment by arn-the-long-beard** [comment]
for examples :
The tests are passing on this 

```rust
extern crate enum_paths;
use enum_paths::*;
use std::str::FromStr;

#[derive(Debug, PartialEq, AsPath)]
enum Route {
    Users(UserRoute),
    #[path = "stuff"]
    Tasks(TaskRoute),
    #[path= ""]
    Empty,
}

#[derive(Debug, PartialEq, AsPath)]
enum UserRoute {
    #[path = ""]
    Profile(u32),
    List,
}

#[derive(Debug, PartialEq, AsPath)]
enum TaskRoute {
    Task(TaskInfo),
    #[path = ""]
    List,
}
#[derive(Debug, PartialEq)]
struct TaskInfo {
    id: u32,
}
impl ToString for TaskInfo {
    fn to_string(&self) -> String {
        self.id.to_string()
    }
}
impl FromStr for TaskInfo {
    type Err = <u32 as FromStr>::Err;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        FromStr::from_str(s)
            .map(|id| Self { id })
    }
}
#[test]
fn as_path() {
    assert_eq!(
        Route::Users(UserRoute::Profile(1)).as_path(),
        "/users/1"
    );
    assert_eq!(
        Route::Users(UserRoute::List).as_path(),
        "/users/list"
    );
    assert_eq!(
        Route::Tasks(TaskRoute::Task(TaskInfo { id: 1 })).as_path(),
        "/stuff/task/1"
    );
    assert_eq!(
        Route::Tasks(TaskRoute::List).as_path(),
        "/stuff"
    );
    assert_eq!(
        Route::Empty.as_path(),
        ""
    );
}
#[test]
fn parse_path() {
    assert_eq!(
        Route::parse_path("/users/1").unwrap(),
        Route::Users(UserRoute::Profile(1)),
    );
    assert_eq!(
        Route::parse_path("users/1").unwrap(),
        Route::Users(UserRoute::Profile(1)),
    );
    assert_eq!(
        Route::parse_path("/users/list").unwrap(),
        Route::Users(UserRoute::List),
    );
    assert_eq!(
        Route::parse_path("/stuff/task/1").unwrap(),
        Route::Tasks(TaskRoute::Task(TaskInfo { id: 1 })),
    );
    assert_eq!(
        Route::parse_path("/stuff///task///2").unwrap(),
        Route::Tasks(TaskRoute::Task(TaskInfo { id: 2 })),
    );
    assert_eq!(
        Route::parse_path("/stuff").unwrap(),
        Route::Tasks(TaskRoute::List),
    );
    assert_eq!(
        Route::parse_path("/").unwrap(),
        Route::Empty,
    );
    assert_eq!(
        Route::parse_path("///").unwrap(),
        Route::Empty,
    );
    assert_eq!(
        Route::parse_path("").unwrap(),
        Route::Empty,
    );
}


```

Do you know why it is working there ?

Anyway, maybe we should find an other name since it is a built-in attribute even if it is for `mod`.

**Comment by arn-the-long-beard** [comment]
> If you want to try it out you will also need to change the attribute name in the `#[proc_macro_derive(...)]` part

Hoo I see , I forgot to change it there. But it is working without changing it.

**Comment by mankinskin** [comment]
Ah I see.. when changing it in the `proc_macro_derive(AsPath, attributes(...))` the proc-macro doesn't compile, but when not changing it, I only get a warning in the test module saying `unused attribute`, and the proc-macro still uses it.. 

> Anyway, maybe we should find an other name since it is a built-in attribute even if it is for mod.

Yes I think so too. Especially because it would require us to not mention the attribute in the `attributes` of the `proc_macro_derive`. maybe `route` is a better name?

Actually, originally I called this crate `enum_routes` but then realized that this was basically applicable to any kind of path, so I changed it. `routes` may now be somewhat confusing in context unrelated to routing.

Other options may be `AsPath` or `path_name`.
`path` really would be the perfect attribute name, but I am also fine with `name`.

**Comment by arn-the-long-beard** [comment]
Thank you for your message. I understand a bit more 🙂.

By default we use the Variant to build the path segment and we use the
attribute when we want/need to use a different value for the segment.

Maybe using a verbe like they do in the serde crate for json would be
better.

Something like :

 '#[parse_as_path= "new_path" ]'

It feels sementically very intuitive because it actually describe what is
happening.

We can use the word 'route' for something else 😊 later.

What do you think about it ?




Le jeu. 1 oct. 2020 à 16:03, Linus Behrbohm <notifications@github.com> a
écrit :

**Comment by mankinskin** [comment]
`parse_as_path` is rather long, and also the macro does not only implement a parser from paths but also a converter to paths, so `parse` would be kind of misleading.

But you got me another idea, what about `segment` or `segment_name` or `path_segment`? Hmm I am not sure if any of these alternatives really help a lot. Unless there is a good reason not to use `name` I would leave it as it is.

**Comment by arn-the-long-beard** [comment]
Hoo yes you are right 🙂
 Then let's think more about it.
I should have explained why I want the rename. I come back on it tomorrow 🙂



Le jeu. 1 oct. 2020 à 16:29, Linus Behrbohm <notifications@github.com> a
écrit :

**Comment by arn-the-long-beard** [comment]
Good morning. The reason I would like to change from `name` was because I would like to extract the name/title of the route as well and maybe give the user the possibility to rename a route as well with an attribute.

**Comment by arn-the-long-beard** [comment]
So now it looks like this 

```rust

#[derive(Debug, PartialEq, AsPath)]
enum Route {
    Users(UserRoute),
    #[segment_as = "stuff"]
    Tasks(TaskRoute),
    #[segment_as = ""]
    Empty,
}


```

Then we can use name for something else :)

What do you think ? :)

**Comment by arn-the-long-beard** [comment]
The PR as draft so we can work on it .

I added a `trait` called `Named` to get the name of a route.

The code works good but maybe the naming needs improvement :laughing: .


Here is the result 

with_name_of_routes

Maybe we could add an attribute to rename a route now or later.

**Comment by mankinskin** [comment]
I am not sure if we should add this functionality to this crate. I think this could go into a completely different crate. Then there are probably already crates that do this, like `strum`, but I can see that they don't really offer the simplicity and ergonomics we want.

I am also still unsure if I understand your expected behavior correctly.
```rust
#[AsPath, Named]
enum Route {
    #[name = ""]
    Tasks(TaskRoute),
    Home,
}
#[AsPath, Named]
enum TaskRoute {
    #[name = "Tasks"]
    #[as_path = ""]
    List,
    #[name = "Task"]
    #[as_path = ""]
    Task(u32),
}
```
should render paths as:
```rust
Tasks(List) => /tasks
Tasks(Task(1)) => /tasks/1
Home => /home
```
and names as
```rust
Tasks(List) => Tasks
Tasks(Task(1)) => Task 1
Home => Home
```

So basically the names are "paths" delimited with spaces ` `, and with the default not being snake_case but the enum variant identifier directly as a string.

**Comment by mankinskin** [comment]
Oh yes and I think as an attribute name I find `as_path` rather nice. because it is analogous to the trait name.

**Comment by mankinskin** [comment]
And what do you think of parsing names? It might make the API more complete. I am not sure if you actually need it, but if you do, it would be very handy.

**Comment by mankinskin** [comment]
Wow I just realized I can just push to your fork of this repository... Not very nice :joy:

**Comment by arn-the-long-beard** [comment]
Haha, I think it is nice 😉 and you can do it because you are the owner of
the original repos I guess.

Yes for 'as_path'.

For the name, it should give only the variant, not the fields.

See the screenshot 🙂. I will look more into your messages tomorrow 🙂

Le ven. 2 oct. 2020 à 18:02, Linus Behrbohm <notifications@github.com> a
écrit :

**Comment by mankinskin** [comment]
> For the name, it should give only the variant, not the fields.

Ah I see, that makes it more difficult, because I would like to have fields in the name.. For the `Task 1` for example. 

But just implementing `Named` for `u32` and making it empty isn't good either. Maybe we need an attribute `no_nesting`?

**Comment by arn-the-long-beard** [comment]
Good morning @mankinskin 

Thank you for your commits and messages ! :+1: 

Yes for `as_path`  , it is the best !  :smile:  

> > For the name, it should give only the variant, not the fields.
> 
> Ah I see, that makes it more difficult, because I would like to have fields in the name.. For the `Task 1` for example.
> 
> But just implementing `Named` for `u32` and making it empty isn't good either. Maybe we need an attribute `no_nesting`?

Hoo I see, the issue is that I did not see them as routes actually.

I thought that `Task 1` & `Task 2` were the same route named `Task` and `u32` a `parameter`. Maybe we have a semantic challenge here.

For example in angular I will write 

```ts

export const routes: Routes = [

{path: "task/:id", component: TaskComponent}

];

```

There is no title for route in angular. And if we want to display them in a menu we do it by hand.

```html

   <li [routerLink]="['/task/'+id]"  routerLinkActive="active-link">
        <button mat-button>Task {{id}}</button>
        </li>

```

Also the name in angular can be translated since it is written in html. So maybe we should not have name generated for routes actually.

**Comment by arn-the-long-beard** [comment]
Here is how I did display the nested routes with the current routing system. 

display_nested_routes


```rust


fn render_route(model: &Model) -> Node<Msg> {
    ul![
        li![a![
            C![
                "route",
                IF!( model.router.is_current_route(&Routes::Login) => "active-route" )
            ],
            attrs! { At::Href => model.router.url(&Routes::Login) },
            "Login",
        ]],
        li![a![
            C![
                "route",
                IF!(model.router.is_current_route(&Routes::Register) => "active-route" )
            ],
            attrs! { At::Href => model.router.url(&Routes::Register) },
            "Register",
        ]],
        li![a![
            C![
                "route",
                IF!(model.router.is_current_route(&Routes::NotFound) => "active-route" )
            ],
            attrs! { At::Href => model.router.url(&Routes::NotFound) },
            "NotFound",
        ]],
        li![a![
            C![
                "route",
                IF!(model.router.is_current_route(&Routes::Home) => "active-route" )
            ],
            attrs! { At::Href => model.router.url(&Routes::Home) },
            "Home",
        ]],
        li![a![C!["route"], "Dashboard",]],
        ul![
            li![a![
                C![
                    "route",
                    IF!(model.router.is_current_route(&Routes::Dashboard(DashboardRoutes::Root)) => "active-route" )
                ],
                attrs! { At::Href => model.router.url(&Routes::Dashboard(DashboardRoutes::Root)) },
                "Profile",
            ]],
            li![a![
                C![
                    "route",
                    IF!(model.router.is_current_route(&Routes::Dashboard(DashboardRoutes::Message)) => "active-route" )
                ],
                attrs! { At::Href => model.router.url(&Routes::Dashboard(DashboardRoutes::Message)) },
                "Messages",
            ]],
            li![a![
                C![
                    "route",
                    IF!(model.router.is_current_route(&Routes::Dashboard(DashboardRoutes::Statistics)) => "active-route" )
                ],
                attrs! { At::Href => model.router.url(&Routes::Dashboard(DashboardRoutes::Statistics)) },
                "Statistics",
            ]],
        ],
    ]


```

**Comment by mankinskin** [comment]
> I thought that Task 1 & Task 2 were the same route named Task and u32 a parameter. Maybe we have a semantic challenge here.

Right, that is also a way of doing it.. maybe that should even be the preferred way. My urls for single tasks are `/tasks/{id}` right now, but they could also be made into `/tasks?id={id}`.. good idea actually.

> So maybe we should not have name generated for routes actually.

I also think it is a rather challenging feature to get right. But the idea is good, maybe we will come up with a design eventually. But before that we should probably focus on getting the `seed::Url` type right.

**Comment by arn-the-long-beard** [comment]
I agree :+1:

**Comment by arn-the-long-beard** [comment]
I just see we did not merge the commits. Can we merge it so we validate this step ?

**Comment by mankinskin** [comment]
Oh right, we did change something. But I will put the `Named` API in a separate branch for now and only merge the rename of the `as_path` attribute.

**Comment by arn-the-long-beard** [comment]
I agree :+1: 

Let's keep this PR only about renaming `as_path`

I do check todo on cusom_router PR then :smile:

**Comment by mankinskin** [comment]
I pushed the new branch `named_api` to my repository of this crate, because I was not allowed to create a new branch in this repository. If we ever get back to it, that is where we left off :)

**Comment by arn-the-long-beard** [comment]
Great !!!
Thank you !

**Pull request merged**
